version: "{build}"
clone_folder: c:\gopath\src\github.com\twpayne\go-vfs
environment:
  GOPATH: c:\gopath
install:
  - go version
  - go get -t -v ./...
build_script:
  - go build
test_script:
  - go test -v ./...
